### ISSUE TITLE
DSO error with libocore

### ISSUE THREAD

**Issue by user030276** [sanford1/shmupmametgm#1]
make SUBTARGET=tgm NOWERROR=1
Linking mametgm64...
/usr/bin/ld: obj/sdl/mametgm64/libocore.a(sdlsync_tc.o): undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'
/usr/bin/ld: //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status

fix is 
LDFLAGS = -Wl,--warn-common,--copy-dt-needed-entries # GNU Make 4.2.1

**Comment by MaryHal** [comment]
Nice try User823574, I'm not going to switch back to Linux 😄 

I was able to reproduce this issue in a VM. Another way to solve this problem is to explicitly link pthread, which worked for me. I think I prefer that solution for now.

**Comment by MaryHal** [comment]
Either solution is probably good enough. I wonder if it's worth it to maintain this versus inspecting mainline MAME or groovymame and make any potential improvements there.
